[package]
name = "thetypify"
version = "0.1.0"
edition = "2021"

[dependencies]
near-jsonrpc-client = "0.15.1"
near-jsonrpc-primitives = "0.28.0"
near-primitives = "0.28.0"
reqwest = "0.12.12"
serde = "1.0.218"
serde_json = "1.0.139"
tokio = { version = "1", features = ["full"] }
typify = "0.3.0"
